# RO47002 Machine Learning for Robotics
* (c) TU Delft, 2020
* Period: 2020-2021, Q1
* Course homepage: https://brightspace.tudelft.nl/d2l/home/318952

Make sure you fill in any place that says `YOUR CODE HERE` or `YOUR ANSWER HERE`. Moreover, if you see an empty cell, please DO NOT delete it, instead run that cell as you would run all other cells. Please fill in your name(s) and other required details below:

In [1]:
GROUP_NUMBER = "61"
STUDENT_NAME1 = "Oyono Ramos Lourenco de Armada"                             
STUDENT_NUMBER1 = "4459059"
STUDENT_NAME2 = "Tom Kerssemakers"                             
STUDENT_NUMBER2 = "4345487"

In [2]:
# Note: this block is a check that you have filled in the above information.
# It will throw an AssertionError until all fields are filled
assert(GROUP_NUMBER != "")
assert(STUDENT_NAME1 != "")
assert(STUDENT_NUMBER1 != "")
assert(STUDENT_NAME2 != "")
assert(STUDENT_NUMBER2 != "")

### General announcements

* Do *not* share your solutions, and do *not* copy solutions from others. By submitting your solutions, you claim that you and your lab partner alone are responsible for this code.

* Do *not* email questions directly, since we want to provide everybody with the same information and avoid repeating the same answers. Instead, please post your questions regarding this assignment in the correct support forum on Brightspace, this way everybody can benefit from the response. If you do have a particular question that you want to ask directly, please use the scheduled practicum hours to ask a TA.

* There is a strict deadline for each assignment. Students are responsible to ensure that they have uploaded their work in time. So, please double check that your upload succeeded to the Brightspace and avoid any late penalties.

* This [Jupyter notebook](https://jupyter.org/) uses `nbgrader` to help us with automated tests. `nbgrader` will make various cells in this notebook "uneditable" or "unremovable" and gives them a special id in the cell metadata. This way, when we run our checks, the system will check the existence of the cell ids and verify the number of points and which checks must be run. While there are ways that you can edit the metadata and work around the restrictions to delete or modify these special cells, you should not do that since then our nbgrader backend will not be able to parse your notebook and give you points for the assignment. You are free to add additional cells, but if you find a cell that you cannot modify or remove, please know that this is on purpose.

* This notebook will have in various places a line that throws a `NotImplementedError` exception. These are locations where the assignment requires you to adapt the code! These lines are just there as a reminder for youthat you have not yet adapted that particular piece of code, especially when you execute all the cells. Once your solution code replaced these lines, it should accordingly *not* throw any exceptions anymore.

Before you turn this problem in, make sure everything runs as expected. First, **restart the kernel** (in the menubar, select Kernel$\rightarrow$Restart) and then **run all cells** (in the menubar, select Cell$\rightarrow$Run All).

---

# RO4702 - Practicum week 2 - Annotator

* Topic: Data collection
* Year: 2020-2021
* Book chapters: 2, 3

In [24]:
# Python ≥3.5 is required
import sys
assert sys.version_info >= (3, 5)

# Scikit-Learn ≥0.20 is required
import sklearn
assert sklearn.__version__ >= "0.20"

# Common imports
import numpy as np
import glob, os
import pickle
import skimage
import skimage.transform

# to make this notebook's output stable across runs
np.random.seed(42)

# To plot pretty figures
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

In [25]:
import ipywidgets as widgets
from ipywidgets import interact, interactive, IntSlider
from IPython.display import display

import matplotlib.patches as patches

Replace the path below with the path to your image folder

In [26]:
IMAGE_DIR = 'images/val'

## Get the Data

Read an image, and visualize it

## Load all images

In [27]:
filenames = glob.glob(os.path.join(IMAGE_DIR, '*.jpg'))
filenames = sorted(filenames)
N = len(filenames)
print(f'found {N} images in target directory')

found 9 images in target directory


In [28]:
MAX_SIZE = 512

def load_and_resize_image(filename, overwrite=False):
    print(f'loading "{filename}" ...')
    I = plt.imread(filename)
    
    # is the width or height too large?
    oversize_ratio = max(I.shape[0] / MAX_SIZE, I.shape[1] / MAX_SIZE)
    if oversize_ratio > 1.0:
        print('resizing image ...')
        I = skimage.transform.rescale(I, (1./oversize_ratio, 1/oversize_ratio, 1), anti_aliasing=True)
        
        # overwrite the old image file after resizing
        if overwrite:
            print(f'overwriting "{filename}" ...')
            plt.imsave(filename, I)
            
    return I

In [29]:
overwrite = True

Is = [load_and_resize_image(filename, overwrite) for filename in filenames]
print('loaded %d images' % len(Is))

loading "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (1).jpg" ...
resizing image ...
overwriting "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (1).jpg" ...
loading "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (2).jpg" ...
resizing image ...
overwriting "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (2).jpg" ...
loading "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (3).jpg" ...
resizing image ...
overwriting "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (3).jpg" ...
loading "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (4).jpg" ...
resizing image ...
overwriting "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (4).jpg" ...
loading "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (5).jpg" ...
resizing image ...
overwriting "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (5).jpg" ...
loading "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (6).jpg" ...
resizing image ...
overwriting "images/val/WhatsApp Image 2020-10-25 at 12.19.04 (6).jpg" ...
loading "i

In [27]:
import pickle

annot_filename = os.path.join(IMAGE_DIR, 'annots2.npy')
annot_exists = os.path.isfile(annot_filename)

print(f'Looking for annotations file "{annot_filename}":', 'found' if annot_exists else 'NOT found')

# load annotations
if annot_exists:
    print('Loading annotations')
    annots = pickle.load(open(annot_filename, 'rb'))
else:
    print('Initializing empty annotations array')
    annots = np.zeros((N,4)) # x1, y1, x2, y2

Looking for annotations file "images/fork\annots2.npy": NOT found
Initializing empty annotations array


### Annotate

We will use here `%matplotlib notebook` to enable interactive widgets in this notebook. Interactive widgets can take up a lot of memory howeever, so in other notebooks we might prefer to use `%matplotlib inline` to just save plotted results as images without interaction.

In [28]:
%matplotlib notebook

In [29]:
def annotate_image(idx):
    # load image
    I = Is[idx]

    # create plot
    fig = plt.figure()
    ax = fig.add_subplot(111)
    ax.imshow(I)
    plt_points_tip = ax.plot(annots[idx,0], annots[idx,1], 'gx', label='tip (left click)')[0]
    plt_points_end = ax.plot(annots[idx,2], annots[idx,3], 'rx', label='end (right click)')[0]
    fig.legend()

    def onclick(event):
        cx, cy = event.xdata, event.ydata # don't use x,y
        button = event.button # 1 for left, 2 for right

        if button == 1:
            plt_points_tip.set_xdata([cx])
            plt_points_tip.set_ydata([cy])
            annots[idx,0] = cx
            annots[idx,1] = cy
        else:
            plt_points_end.set_xdata([cx])
            plt_points_end.set_ydata([cy])
            annots[idx,2] = cx
            annots[idx,3] = cy

    fig.canvas.mpl_connect('button_press_event', onclick)

def on_save_button_clicked(b):
    print(f'Saving annotations "{annot_filename}"')
    pickle.dump(annots, open(annot_filename, 'wb'))

save_button = widgets.Button(description="Save changes!")
save_button.on_click(on_save_button_clicked)

In [30]:
interact(annotate_image, idx=IntSlider(min=0, max=len(Is)-1, continuous_update=False))

interactive(children=(IntSlider(value=0, continuous_update=False, description='idx', max=99), Output()), _dom_…

<function __main__.annotate_image(idx)>

### Save your annotations
Run the cell below should give us a buttom "save changes". Click that buttom and save the annotations into 'annots.npy'

In [24]:
display(save_button)

Button(description='Save changes!', style=ButtonStyle())

Saving annotations "images/fork\annots.npy"
Saving annotations "images/fork\annots.npy"
Saving annotations "images/fork\annots2.npy"


In [25]:
annots.shape

(100, 4)

In [26]:
print(annots)

[[158.89391403  87.46535528 391.62118676 418.54760636]
 [129.80300494 109.62985745 437.29708843 380.4596173 ]
 [ 88.24456338 166.42639424 466.80106003 335.46933168]
 [ 66.7947544  217.70380716 465.50595309 272.69845526]
 [ 63.85522048 290.29770406 462.41764717 205.16786535]
 [ 85.21416552 335.10052702 448.80712739 158.98518611]
 [114.10033055 379.87450213 409.84320078 101.42653659]
 [168.45667661 425.22880533 322.42396311  54.22329569]
 [250.52956202 430.72231218 226.92581349  31.27426024]
 [321.08571131 414.39055311 160.19132918  51.02234177]
 [373.81849469 392.98239737 126.68700119  75.74267876]
 [416.39740352 336.90324691  73.4106365  123.13475025]
 [444.89492946 259.31447937  42.25407535 202.8034823 ]
 [447.9824107  233.52558619  40.09157492 246.45170423]
 [426.40954776 146.68561281  73.55392989 343.58294654]
 [437.72791655 251.69711913  79.93098621 440.53438792]
 [432.7905675   99.56370968  37.69595606  49.12609971]
 [412.64951393 108.47954316  77.3277902  335.75315591]
 [201.4700